# [START container_node_deployment]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-apiserver
  template:
    metadata:
      labels:
        app: node-apiserver
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: node-apiserver
        image: docker.io/olalab/node-apiserver:v1
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: 200Mi
          limits:
            memory: 800Mi
        env:
          - name: MONGO_CONNSTR
            value: mongodb://mongo-svc.default
          - name: OKTA_ISSUER
            value: https://dev-850265.okta.com/oauth2/default
          - name: OKTA_CLIENT_ID
            value: 0oanbr1foevIkjf8c4x6
---
apiVersion: v1
kind: Service
metadata:
  name: node-apiserver-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: node-apiserver
# [END container_node_deployment]